### PR TITLE
demo day video

### PR DESCRIPTION
**Pull request by timherzig**

### CODE REVIEW

**Review by QW3RAT — APPROVED** [review]
Lgtm. I like the runtime diagram

**Comment by emuguy1** [comment]
Two things that we could improve just by looking at the beginning.
1. Is there a way to improve the resolution of the video, I think if not, then it is okay that
2. The Audio for me at least is mono on the Left speaker. Therefore it is pretty quiet. Can you maybe increase the video's volume and make it play on both speaker sides?

Other than that I like that it shows how easy it is to use our plugin. And the sentence with the test.test..test..test..tests

**Comment by nikomall34** [comment]
Very nice video guys!!
I also have the same remarks as @emuguy1. But if you dont find a quick way to fix it I wouldn't mind.

**Review by nikomall34 — APPROVED** [review]

**Comment by timherzig** [comment]
I think I fixed the audio. (we edited on a laptop and didn't notice the mono audio :) For the quality I don't know how to increase it, I tried rendering at a higher resolution but it didn't change anything...

**Review by nikomall34 — APPROVED** [review]
Audio is fixed!

**Pull request merged**
