### PR TITLE
Feature/100 html parser

### PR DESCRIPTION
**Pull request by QW3RAT**
Added the parser and a rudimentary testing class for it also

### CODE REVIEW

**Comment by QW3RAT** [comment]
Linting fails because of error in testfile i dont want to change, to be as close to the real reports we will work with as possible

**Review by lfogarty98 — COMMENTED** [review]
Looks good to me, I like that there is now a data structure which captures both the current-scope results as well as the related package results. 

A question though: how are you handling the "mutation-specific" results such as those handled by the XML parser? For instance, line number is important since this is required for displaying the color bars after a Pitest run, so I think we do need to be able to obtain this.

**Comment by lheimbs** [comment]
Linter fixes are merged. Please rebase to re-lint

**Comment by QW3RAT** [comment]
I now get linting errors in parrt of the programm where i didnt changed anything :(. I'll have a look into that

**Pull request closed without merging**
