### PR TITLE
Added the build file check to the RunConfigurationAction

### PR DESCRIPTION
**Pull request by nikomall34**
Now before the pitest run is executed it is tested if the necessary plugins are included.

### CODE REVIEW

**Review by lheimbs — APPROVED** [review]
This could nicely be implemented as a Service, see for example the `UdpMessagingServer` or here: https://plugins.jetbrains.com/docs/intellij/plugin-services.html

**Comment by nikomall34** [comment]
Good idea! I will do that.

**Comment by nikomall34** [comment]
Ok I implemented the class as a Service now

**Review by lheimbs — APPROVED** [review]
:+1:

**Pull request merged**
